name: mosaic
description: "Mosaic is a modular architecture for Flutter that enables clean separation of features using dynamic modules, internal events, UI injection, and centralized builds "
version: 1.0.7
homepage: "https://github.com/marcomit/mosaic"
repository: "https://github.com/marcomit/mosaic"

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.3
  argv: ^1.0.7
  path: ^1.9.1

executables:
  mosaic: bin

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.25.15
